### ISSUE TITLE
links to geophysics grids not working

### ISSUE THREAD

**Issue by markjessell** [GeoscienceAustralia/geophys_utils#7]
The links defined by:

netcdf_path ="http://dapds00.nci.org.au/thredds/dodsC/rr2/national_geophysical_compilations/magmap_v6_2015_VRTP/magmap_v6_2015_VRTP.nc"
netcdf_path ="http://dapds00.nci.org.au/thredds/dodsC/rr2/national_geophysical_compilations/IR_gravity_anomaly_Australia_V1/IR_gravity_anomaly_Australia_V1.nc"

return:

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-4-ad04a079fd04> in <module>
     14 netcdf_path ="http://dapds00.nci.org.au/thredds/dodsC/rr2/national_geophysical_compilations/magmap_v6_2015_VRTP/magmap_v6_2015_VRTP.nc"
     15 netcdf_path ="http://dapds00.nci.org.au/thredds/dodsC/rr2/national_geophysical_compilations/IR_gravity_anomaly_Australia_V1/IR_gravity_anomaly_Australia_V1.nc"
---> 16 netcdf_dataset = netCDF4.Dataset(netcdf_path, 'r')
     17 
     18 max_bytes = 500000000

netCDF4\_netCDF4.pyx in netCDF4._netCDF4.Dataset.__init__()

netCDF4\_netCDF4.pyx in netCDF4._netCDF4._ensure_nc_success()

OSError: [Errno -72] NetCDF: Malformed or inaccessible DAP DDS: b'http://dapds00.nci.org.au/thredds/dodsC/rr2/national_geophysical_compilations/IR_gravity_anomaly_Australia_V1/IR_gravity_anomaly_Australia_V1.nc'

**Comment by andrew-j-turner-000** [comment]
Hi @markjessell the links to the geophysics datasets have now been updated in the example jupyter notebooks, with the exception of the AEM dataset links which will be updated when the netCDFs are ready.

**Comment by markjessell** [comment]
thanks, much appreciated.
